#root:
#    path: /
#    defaults:
#        _controller: FrameworkBundle:Redirect:urlRedirect
#        path: /cbo/viewImportFileCBO
#        permanent: true

new_cbo:
    resource: "@NewCBOBundle/Controller/"
    type:     annotation
    prefix:   /

convenio:
    resource: "@CallCenterBundle/Controller/ConveniosController.php"
    type:     annotation
    prefix:   /convenio

agencia:
    resource: "@CallCenterBundle/Controller/AgenciasController.php"
    type:     annotation
    prefix:   /agencia

call_center:
    resource: "@CallCenterBundle/Controller/"
    type:     annotation
    prefix:   /callcenter

agentes:
    resource: "@NewCBOBundle/Controller/AgentesController.php"
    prefix:   /agentes
    type:     annotation

security:
    resource: "@UserBundle/Controller/"
    type:     annotation
    prefix:   /user



